name: Build GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Build GitHub Pages
      run: |
        npm install
        mkdir public/scripts
        npm run build
        cd public
        git init
        git remote add origin https://github.com/mweir-mcst/tight-squeeze.git
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add .
        git commit -m "GitHub Pages" --author "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
        git branch gh-pages
        header=$(echo -n "ad-m:${GH_TOKEN}" | base64)
        git -c http.extraheader="AUTHORIZATION: basic $header" push --force -u origin gh-pages
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
